spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vision
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect